# Repositorio espelhado: https://gitlab.com/junio.pereir/Workshop-CI-Entrega-02

stages:
  - build
  - test

image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HUB_USER: $DOCKER_HUB_USER
  DOCKER_HUB_PASS: $DOCKER_HUB_PASS

build-frontend:
  stage: build
  before_script:
    - echo "BUILDING FRONTEND..."
    - echo "$DOCKER_HUB_PASS" | docker login -username $DOCKER_HUB_USER --password-stdin
    - docker pull $DOCKER_HUB_USER/gces-frontend:build-frontend
  script:
    - docker build -f ./frontend/Dockerfile -t $DOCKER_HUB_USER/gces-frontend:build-frontend ./frontend
    - docker push $DOCKER_HUB_USER/gces-frontend:build-frontend
  after_script:
    - echo "Frontend built successfully..."

build-backend:
  stage: build
  before_script:
    - echo "BUILDING BACKEND..."
    - echo "$DOCKER_HUB_PASS" | docker login -username $DOCKER_HUB_USER --password-stdin
    - docker pull $DOCKER_HUB_USER/gces-backend:build-backend
  script:
    - docker build -f ./backend/Dockerfile -t $DOCKER_HUB_USER/gces-backend:build-backend ./backend
    - docker push $DOCKER_HUB_USER/gces-backend:build-backend
  after_script:
    - echo "Backend built successfully..."

test-backend:
  image: docker/compose:stable
  stage: test
  before_script:
    - echo "TESTING BACKEND..."
  script:
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Backend tested successfully..."

test-frontend:
  image: docker/compose:stable
  stage: test
  before_script:
    - echo "TESTING FRONTEND..."
  script:
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "Frontend tested successfully..."
