# Repositorio espelhado: https://gitlab.com/junio.pereir/Workshop-CI-Entrega-02

stages:
  - build
  - test

image: docker:20.10.8

services:
  - docker:dind

variables:
  DOCKER_HUB_USER: $DOCKER_HUB_USER
  DOCKER_HUB_PASS: $DOCKER_HUB_PASS

before_script:
  - docker login -u $DOCKER_HUB_USER --password-stdin

build-frontend:
  stage: build
  before_script:
    - echo "BUILDING FRONTEND..."
  script:
    - docker build --cache-from damasojunio/gces-frontend ./frontend
    - docker push damasojunio/gces-frontend
  after_script:
    - echo "Frontend built successfully..."

build-backend:
  stage: build
  before-script:
    - echo "BUILDING BACKEND..."
  script:
    - docker build --cache-from damasojunio/gces-backend ./backend
    - docker push damasojunio/gces-backend
  after-script:
    - echo "Backend built successfully..."

test-backend:
  image: docker/compose
  stage: test
  before_script:
    - echo "TESTING BACKEND..."
  script:
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Backend tested successfully..."

test-frontend:
  image: docker/compose
  stage: test
  before_script:
    - echo "TESTING FRONTEND..."
  script:
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "Frontend tested successfully..."
